CREATE DATABASE IF NOT EXISTS IMMERSIVEMIND;

USE IMMERSIVEMIND;

CREATE TABLE IF NOT EXISTS CUIDADORES 
(	
	EMAIL_ID VARCHAR(20) NOT NULL,
	PRIMEIRO_NOME VARCHAR(20) NOT NULL,
	ULTIMO_NOME VARCHAR(20) NOT NULL,
	PROFISSAO VARCHAR(20),
	PASSWORD VARCHAR(64) NOT NULL,
	LOGGED_IN BOOL NOT NULL,
	PRIMARY KEY (EMAIL_ID)
);

CREATE TABLE IF NOT EXISTS DOENTES 
(
	DOENTE_ID INT AUTO_INCREMENT, 
	PRIMEIRO_NOME VARCHAR(20) NOT NULL,
	ULTIMO_NOME VARCHAR(20) NOT NULL,
	IDADE VARCHAR(6) NOT NULL,
	OBSERVACAO TEXT,
	EMAIL_ID VARCHAR(20) NOT NULL,
	PRIMARY KEY (DOENTE_ID), 
	FOREIGN KEY (EMAIL_ID) REFERENCES CUIDADORES(EMAIL_ID)
);

CREATE TABLE IF NOT EXISTS SESSAO 
(
	SESSAO_ID INT AUTO_INCREMENT, 
	SESSAO_NOME VARCHAR(20) NOT NULL,
	EMAIL_ID VARCHAR(20) NOT NULL,
	DOENTE_ID INT NOT NULL,
	PRIMARY KEY (SESSAO_ID),
	FOREIGN KEY (DOENTE_ID) REFERENCES DOENTES(DOENTE_ID), 
	FOREIGN KEY (EMAIL_ID) REFERENCES CUIDADORES(EMAIL_ID)
);

CREATE TABLE IF NOT EXISTS VIDEOS 
(
	VIDEO_TITLE VARCHAR(100) NOT NULL, -- O titulo do video no Youtube
	SESSAO_ID INT NOT NULL, 
	URL_THUMBNAIL VARCHAR(100) NOT NULL, -- URL onde está localizado o thumbnail
	URL_FILE TEXT NOT NULL, -- URL onde está localizado o ficheiro
	FOREIGN KEY (SESSAO_ID) REFERENCES SESSAO(SESSAO_ID)
);

CREATE TABLE IF NOT EXISTS VIDEOS_OBSERVACAO 
(
	VIDEO_TITLE VARCHAR(100) NOT NULL,
	EMAIL_ID VARCHAR(20) NOT NULL,
	DOENTE_ID INT NOT NULL,
	SESSAO_ID INT NOT NULL, 
	OBSERVACAO TEXT,
	FOREIGN KEY (DOENTE_ID) REFERENCES DOENTES(DOENTE_ID), 
	FOREIGN KEY (EMAIL_ID) REFERENCES DOENTES(EMAIL_ID),
	FOREIGN KEY (SESSAO_ID) REFERENCES SESSAO(SESSAO_ID)
);


